# Generated by Django 4.1.7 on 2023-03-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='subjects',
            new_name='subject',
        ),
    ]
