# Generated by Django 4.1.7 on 2023-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Aceptado'), ('Completed', 'completado'), ('Canceled', 'Cancelado'), ('new', 'Nuevo')], default='New', max_length=50),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='Variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='Variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
