# Generated by Django 4.1.7 on 2023-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('Completed', 'completado'), ('Accepted', 'Aceptado'), ('new', 'Nuevo')], default='New', max_length=50),
        ),
    ]
