# Generated by Django 4.1.7 on 2023-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('Canceled', 'Cancelado'), ('Accepted', 'Aceptado'), ('Completed', 'completado')], default='New', max_length=50),
        ),
    ]
