# Generated by Django 4.1.7 on 2023-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('Completed', 'completado'), ('new', 'Nuevo'), ('Accepted', 'Aceptado')], default='New', max_length=50),
        ),
    ]
