# Generated by Django 4.1.7 on 2023-03-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Cancelado'), ('Accepted', 'Aceptado'), ('Completed', 'completado'), ('new', 'Nuevo')], default='New', max_length=50),
        ),
    ]
